version: '3.8'

services:
  # CockroachDB cluster de 2 nodos (puedes agregar más nodos si lo deseas)
  cockroachdb-node1:
    image: cockroachdb/cockroach:v23.1.11
    command: start --insecure --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3
    hostname: cockroachdb-node1
    ports:
      - "26257:26257"
      - "8081:8080"
    volumes:
      - cockroach-data1:/cockroach/cockroach-data
    networks:
      - app-network

  cockroachdb-node2:
    image: cockroachdb/cockroach:v23.1.11
    command: start --insecure --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3
    hostname: cockroachdb-node2
    ports:
      - "26258:26257" # Puerto SQL diferente para evitar conflictos
      - "8082:8080"   # Puerto UI diferente
    volumes:
      - cockroach-data2:/cockroach/cockroach-data
    networks:
      - app-network
    depends_on:
      - cockroachdb-node1
    
  cockroachdb-node3:
    image: cockroachdb/cockroach:v23.1.11
    command: start --insecure --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3
    hostname: cockroachdb-node3
    ports:
      - "26259:26257"
      - "8083:8080"
    volumes:
      - cockroach-data3:/cockroach/cockroach-data
    networks:
      - app-network
    depends_on:
      - cockroachdb-node1
      - cockroachdb-node2

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  # Kong API Gateway
  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./kong.yml:/kong/declarative/kong.yml
    networks:
      - app-network
    depends_on:
      - usuarios
      - categorias
    restart: unless-stopped

  # Microservicio de usuarios
  usuarios:
    build: ./usuarios
    ports:
      - "3000:3000"
    environment:
      DB_HOST: cockroachdb-node1
      DB_PORT: 26257
      DB_NAME: usuariosdb
      DB_USER: root
      DB_PASSWORD: ""
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      JWT_SECRET: supersecreto123
      PORT: 3000
      NODE_ENV: development
    depends_on:
      - cockroachdb-node1
      - rabbitmq
    networks:
      - app-network

  # Microservicio de categorias
  categorias:
    build: ./categorias
    ports:
      - "3001:3001"
    environment:
      DB_HOST: cockroachdb-node1
      DB_PORT: 26257
      DB_NAME: categoriasdb
      DB_USER: root
      DB_PASSWORD: ""
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      JWT_SECRET: supersecreto123
      PORT: 3001
      NODE_ENV: development
    depends_on:
      - cockroachdb-node1
      - rabbitmq
    networks:
      - app-network

  # Microservicio de eventos
  eventos:
    build: ./eventos
    ports:
      - "3002:3002"
    environment:
      DB_HOST: cockroachdb-node3
      DB_PORT: 26257
      DB_NAME: eventosdb
      DB_USER: root
      DB_PASSWORD: ""
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      JWT_SECRET: supersecreto123
      PORT: 3002
      NODE_ENV: development
    depends_on:
      - cockroachdb-node1
      - rabbitmq
    networks:
      - app-network

volumes:
  cockroach-data1:
  cockroach-data2:
  cockroach-data3:

networks:
  app-network:
    driver: bridge