version: '3.8'

services:
  # CockroachDB cluster de 7 nodos
  cockroachdb-node1:
    image: cockroachdb/cockroach:v23.1.11
    command: start --insecure --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3,cockroachdb-node4,cockroachdb-node5,cockroachdb-node6,cockroachdb-node7
    hostname: cockroachdb-node1
    ports:
      - "26257:26257"
      - "8081:8080"
    volumes:
      - cockroach-data1:/cockroach/cockroach-data

    #cockroachdb-node2:
    # image: cockroachdb/cockroach:v23.1.11
    # command: start --insecure --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3,cockroachdb-node4,cockroachdb-node5,cockroachdb-node6,cockroachdb-node7
    # hostname: cockroachdb-node2
    # ports:
    #   - "26258:26257"
    #   - "8082:8080"
    # volumes:
    #   - cockroach-data2:/cockroach/cockroach-data

    # cockroachdb-node3:
    #   image: cockroachdb/cockroach:v23.1.11
    #   command: start --insecure --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3,cockroachdb-node4,cockroachdb-node5,cockroachdb-node6,cockroachdb-node7
    #   hostname: cockroachdb-node3
    #   ports:
    #     - "26259:26257"
    #     - "8083:8080"
    #   volumes:
    #     - cockroach-data3:/cockroach/cockroach-data

    # cockroachdb-node4:
    #   image: cockroachdb/cockroach:v23.1.11
    #   command: start --insecure --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3,cockroachdb-node4,cockroachdb-node5,cockroachdb-node6,cockroachdb-node7
    #   hostname: cockroachdb-node4
    #   ports:
    #     - "26260:26257"
    #     - "8084:8080"
    #   volumes:
    #     - cockroach-data4:/cockroach/cockroach-data

    # cockroachdb-node5:
    #   image: cockroachdb/cockroach:v23.1.11
    #   command: start --insecure --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3,cockroachdb-node4,cockroachdb-node5,cockroachdb-node6,cockroachdb-node7
    #   hostname: cockroachdb-node5
    #   ports:
    #     - "26261:26257"
    #     - "8085:8080"
    #   volumes:
    #     - cockroach-data5:/cockroach/cockroach-data

    # cockroachdb-node6:
    #   image: cockroachdb/cockroach:v23.1.11
    #   command: start --insecure --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3,cockroachdb-node4,cockroachdb-node5,cockroachdb-node6,cockroachdb-node7
    #   hostname: cockroachdb-node6
    #   ports:
    #     - "26262:26257"
    #     - "8086:8080"
    #   volumes:
    #     - cockroach-data6:/cockroach/cockroach-data

    # cockroachdb-node7:
    #   image: cockroachdb/cockroach:v23.1.11
    #   command: start --insecure --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3,cockroachdb-node4,cockroachdb-node5,cockroachdb-node6,cockroachdb-node7
    #   hostname: cockroachdb-node7
    #   ports:
    #     - "26263:26257"
    #     - "8087:8080"
    #   volumes:
    #     - cockroach-data7:/cockroach/cockroach-data

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  # Kong API Gateway
  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./kong.yml:/kong/declarative/kong.yml

  # Microservicio de usuarios
  usuarios:
    build: ./usuarios
    ports:
      - "3000:3000"
    environment:
      DB_HOST: cockroachdb-node1
      DB_PORT: 26257
      DB_NAME: usuariosdb
      DB_USER: root
      DB_PASSWORD: ""
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      JWT_SECRET: supersecreto123
      PORT: 3000
      NODE_ENV: development
    depends_on:
      - cockroachdb-node1
      - rabbitmq

  # Aquí puedes agregar más microservicios, por ejemplo:
  # categorias, eventos, compras, etc.
  # Solo copia y ajusta el bloque de "usuarios" para cada uno.

volumes:
  cockroach-data1:
  cockroach-data2:
  cockroach-data3:
 
 # cockroach-data4:
 # cockroach-data5:
  #cockroach-data6:
 # cockroach-data7: